<?php

// =======================
// Database configuration.
// =======================

$dbms = 'mysql';
$table_prefix = 'phpbb_';

// ==============================
// PHPBB autogenerated constants.
// ==============================

define( 'PHPBB_INSTALLED', true );